In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../DataSet/09_cotent.csv")
df.head()

   ID  Name    Age  Gender   Salary    City
0   1   Ali   22.0    Male  25000.0  Jaipur
1   2  Sara   25.0  Female  30000.0   Delhi
2   3  John    NaN    Male  35000.0  Mumbai
3   4   Ali   22.0    Male  25000.0  Jaipur
4   5  Emma  150.0  Female      NaN   Delhi

### Dataset Overview and Basic Exploration
- `head()` / `tail()`: View first/last rows
- `describe()`: Statistical summary of numerical columns
- `info()`: Column data types and non-null counts
- `sample()`: Random sample of rows
- `shape`: Dimensionality of the DataFrame
- `columns`: List of column names
- `index`: Index range
- `dtypes`: Data types of each column

In [3]:
df.head()

   ID  Name    Age  Gender   Salary    City
0   1   Ali   22.0    Male  25000.0  Jaipur
1   2  Sara   25.0  Female  30000.0   Delhi
2   3  John    NaN    Male  35000.0  Mumbai
3   4   Ali   22.0    Male  25000.0  Jaipur
4   5  Emma  150.0  Female      NaN   Delhi

In [4]:
df.tail()

    ID    Name    Age  Gender    Salary    City
15  16  Simran   28.0  Female   47000.0  Jaipur
16  17   Rohit   30.0    Male   55000.0  Mumbai
17  18   Kavya   27.0  Female   44000.0   Delhi
18  19   Vikas  120.0    Male  250000.0  Jaipur
19  20   Pooja    NaN  Female   39000.0  Mumbai

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      20 non-null     int64
 1   Name    20 non-null     object
 2   Age     18 non-null     float64
 3   Gender  20 non-null     object
 4   Salary  19 non-null     float64
 5   City    19 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

In [6]:
df.describe()

             ID         Age         Salary
count  20.00000   18.000000      19.000000
mean   10.50000   37.000000   50894.736842
std     5.91608   36.930778   49406.358944
min     1.00000   -5.000000   25000.000000
25%     5.75000   24.000000   31500.000000
50%    10.50000   27.000000   39000.000000
75%    15.25000   29.750000   48500.000000
max    20.00000  150.000000  250000.000000

In [7]:
df.sample(5)

    ID    Name    Age  Gender    Salary    City
16  17   Rohit   30.0    Male   55000.0  Mumbai
6    7    Anna   24.0  Female   32000.0  Jaipur
15  16  Simran   28.0  Female   47000.0  Jaipur
18  19   Vikas  120.0    Male  250000.0  Jaipur
2    3    John    NaN    Male   35000.0  Mumbai

In [8]:
df.shape

(20, 6)

In [9]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [10]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Salary', 'City'], dtype='object')

In [11]:
df.dtypes

ID          int64
Name       object
Age       float64
Gender     object
Salary    float64
City       object
dtype: object

### Missing Values Analysis
Identify columns with missing values and analyze their counts.

In [12]:
df.isnull().sum()

ID        0
Name      0
Age       2
Gender    0
Salary    1
City      1
dtype: int64

In [13]:
df.isnull().sum().sum()

np.int64(4)

In [14]:
df["Age"].median()

27.0

In [15]:
df["Age"].mean()

np.float64(37.0)

### Missing Value Imputation
- Fill missing `Age` with the median age.
- Fill missing `Salary` with the mean salary.
- Fill missing `City` with the mode (most frequent) city.

In [16]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df.isnull().sum()

ID        0
Name      0
Age       0
Gender    0
Salary    1
City      1
dtype: int64

In [17]:
df["Salary"] = df["Salary"].fillna(round(df["Salary"].mean()))
df.isnull().sum()

ID        0
Name      0
Age       0
Gender    0
Salary    0
City      1
dtype: int64

In [18]:
df["City"] = df["City"].fillna(df["City"].mode()[0])
df.isnull().sum()

ID        0
Name      0
Age       0
Gender    0
Salary    0
City      0
dtype: int64

### Duplicate Records Handling
Find and drop duplicate rows in the dataset.

In [19]:
print("Total duplicates:", df.duplicated().sum())
df[df.duplicated(keep=False)]

Total duplicates: 0

Empty DataFrame
Columns: [ID, Name, Age, Gender, Salary, City]
Index: []

In [20]:
df = df.drop_duplicates()
print("Shape after dropping duplicates:", df.shape)

Shape after dropping duplicates: (20, 6)

### Outlier Detection using the IQR Method
1. Calculate First Quartile ($Q_1$) and Third Quartile ($Q_3$).
2. Calculate Interquartile Range ($IQR = Q_3 - Q_1$).
3. Define boundaries: `lower_limit = Q1 - 1.5 * IQR`, `upper_limit = Q3 + 1.5 * IQR`.
4. Filter out data points lying outside these boundaries.

In [21]:
# Calculate Q1 and Q3
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Define bounds
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print(f"Q1: {Q1}, Q3: {Q3}, IQR: {IQR}")
print(f"Lower Bound: {lower_limit}, Upper Bound: {upper_limit}")

# Filter Outliers
df_clean = df[(df["Age"] >= lower_limit) & (df["Age"] <= upper_limit)]
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)
df_clean

Q1: 24.0, Q3: 29.25, IQR: 5.25
Lower Bound: 16.125, Upper Bound: 37.125
Original shape: (20, 6)
Cleaned shape: (17, 6)

    ID    Name   Age  Gender   Salary    City
0    1     Ali  22.0    Male  25000.0  Jaipur
1    2    Sara  25.0  Female  30000.0   Delhi
2    3    John  27.0    Male  35000.0  Mumbai
3    4     Ali  22.0    Male  25000.0  Jaipur
5    6     Tom  28.0    Male  45000.0  Jaipur
6    7    Anna  24.0  Female  32000.0  Jaipur
8    9    Aman  27.0    Male  38000.0   Delhi
9   10   Priya  26.0  Female  42000.0  Jaipur
10  11   Rahul  29.0    Male  50000.0  Mumbai
11  12    Neha  31.0  Female  52000.0   Delhi
12  13   Karan  24.0    Male  34000.0  Jaipur
13  14   Meera  23.0  Female  31000.0  Mumbai
14  15   Arjun  35.0    Male  65000.0   Delhi
15  16  Simran  28.0  Female  47000.0  Jaipur
16  17   Rohit  30.0    Male  55000.0  Mumbai
17  18   Kavya  27.0  Female  44000.0   Delhi
19  20   Pooja  27.0  Female  39000.0  Mumbai

In [22]:
# Save to the same directory as your notebook
df_clean.to_csv("cleaned_practice_data.csv", index=False)