In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [132]:
df = pd.read_csv("../../DataSet/09_cotent.csv")
df

    ID    Name    Age  Gender    Salary    City
0    1     Ali   22.0    Male   25000.0  Jaipur
1    2    Sara   25.0  Female   30000.0   Delhi
2    3    John    NaN    Male   35000.0  Mumbai
3    4     Ali   22.0    Male   25000.0  Jaipur
4    5    Emma  150.0  Female       NaN   Delhi
5    6     Tom   28.0    Male   45000.0     NaN
6    7    Anna   24.0  Female   32000.0  Jaipur
7    8   David   -5.0    Male   28000.0  Mumbai
8    9    Aman   27.0    Male   38000.0   Delhi
9   10   Priya   26.0  Female   42000.0  Jaipur
10  11   Rahul   29.0    Male   50000.0  Mumbai
11  12    Neha   31.0  Female   52000.0   Delhi
12  13   Karan   24.0    Male   34000.0  Jaipur
13  14   Meera   23.0  Female   31000.0  Mumbai
14  15   Arjun   35.0    Male   65000.0   Delhi
15  16  Simran   28.0  Female   47000.0  Jaipur
16  17   Rohit   30.0    Male   55000.0  Mumbai
17  18   Kavya   27.0  Female   44000.0   Delhi
18  19   Vikas  120.0    Male  250000.0  Jaipur
19  20   Pooja    NaN  Female   39000.0  Mumbai

 - head() , tail() , describe() , info() sample()
 - shape ,  columns , shape , index , dtypes ,

In [4]:
df.head()

   ID  Name    Age  Gender   Salary    City
0   1   Ali   22.0    Male  25000.0  Jaipur
1   2  Sara   25.0  Female  30000.0   Delhi
2   3  John    NaN    Male  35000.0  Mumbai
3   4   Ali   22.0    Male  25000.0  Jaipur
4   5  Emma  150.0  Female      NaN   Delhi

In [5]:
df.tail()

    ID    Name    Age  Gender    Salary    City
15  16  Simran   28.0  Female   47000.0  Jaipur
16  17   Rohit   30.0    Male   55000.0  Mumbai
17  18   Kavya   27.0  Female   44000.0   Delhi
18  19   Vikas  120.0    Male  250000.0  Jaipur
19  20   Pooja    NaN  Female   39000.0  Mumbai

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      20 non-null     int64
 1   Name    20 non-null     object
 2   Age     18 non-null     float64
 3   Gender  20 non-null     object
 4   Salary  19 non-null     float64
 5   City    19 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

In [12]:
df.describe()

             ID         Age         Salary
count  20.00000   18.000000      19.000000
mean   10.50000   37.000000   50894.736842
std     5.91608   36.930778   49406.358944
min     1.00000   -5.000000   25000.000000
25%     5.75000   24.000000   31500.000000
50%    10.50000   27.000000   39000.000000
75%    15.25000   29.750000   48500.000000
max    20.00000  150.000000  250000.000000

In [8]:
df.sample()

   ID   Name   Age  Gender   Salary    City
9  10  Priya  26.0  Female  42000.0  Jaipur

In [6]:
df.shape

(20, 6)

In [ ]:
df.index

In [7]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Salary', 'City'], dtype='object')

In [13]:
df.dtypes

ID          int64
Name       object
Age       float64
Gender     object
Salary    float64
City       object
dtype: object

# missing values anlysis

In [20]:
df.isnull().sum()

ID        0
Name      0
Age       2
Gender    0
Salary    1
City      1
dtype: int64

In [21]:
df.isna().sum().sum()

np.int64(4)

In [28]:
df["Age"].median()

27.0

In [31]:
# df["Age"]

In [32]:
df["Age"].mean()

np.float64(37.0)

# fill the is na or null value

In [120]:
df["Age"]=df["Age"].fillna(df["Age"].median())
df

    ID    Name    Age  Gender    Salary    City
0    1     Ali   22.0    Male   25000.0  Jaipur
1    2    Sara   25.0  Female   30000.0   Delhi
2    3    John   27.0    Male   35000.0  Mumbai
3    4     Ali   22.0    Male   25000.0  Jaipur
4    5    Emma  150.0  Female       NaN   Delhi
5    6     Tom   28.0    Male   45000.0     NaN
6    7    Anna   24.0  Female   32000.0  Jaipur
7    8   David   -5.0    Male   28000.0  Mumbai
8    9    Aman   27.0    Male   38000.0   Delhi
9   10   Priya   26.0  Female   42000.0  Jaipur
10  11   Rahul   29.0    Male   50000.0  Mumbai
11  12    Neha   31.0  Female   52000.0   Delhi
12  13   Karan   24.0    Male   34000.0  Jaipur
13  14   Meera   23.0  Female   31000.0  Mumbai
14  15   Arjun   35.0    Male   65000.0   Delhi
15  16  Simran   28.0  Female   47000.0  Jaipur
16  17   Rohit   30.0    Male   55000.0  Mumbai
17  18   Kavya   27.0  Female   44000.0   Delhi
18  19   Vikas  120.0    Male  250000.0  Jaipur
19  20   Pooja   27.0  Female   39000.0  Mumbai

In [121]:
# salary 
df["Salary"]=df["Salary"].fillna(round(df["Salary"].mean()))
df

    ID    Name    Age  Gender    Salary    City
0    1     Ali   22.0    Male   25000.0  Jaipur
1    2    Sara   25.0  Female   30000.0   Delhi
2    3    John   27.0    Male   35000.0  Mumbai
3    4     Ali   22.0    Male   25000.0  Jaipur
4    5    Emma  150.0  Female   50895.0   Delhi
5    6     Tom   28.0    Male   45000.0     NaN
6    7    Anna   24.0  Female   32000.0  Jaipur
7    8   David   -5.0    Male   28000.0  Mumbai
8    9    Aman   27.0    Male   38000.0   Delhi
9   10   Priya   26.0  Female   42000.0  Jaipur
10  11   Rahul   29.0    Male   50000.0  Mumbai
11  12    Neha   31.0  Female   52000.0   Delhi
12  13   Karan   24.0    Male   34000.0  Jaipur
13  14   Meera   23.0  Female   31000.0  Mumbai
14  15   Arjun   35.0    Male   65000.0   Delhi
15  16  Simran   28.0  Female   47000.0  Jaipur
16  17   Rohit   30.0    Male   55000.0  Mumbai
17  18   Kavya   27.0  Female   44000.0   Delhi
18  19   Vikas  120.0    Male  250000.0  Jaipur
19  20   Pooja   27.0  Female   39000.0  Mumbai

In [122]:
# City 
df["City"]=df["City"].fillna(df["City"].mode()[0])
df["City"].mode()[0]

'Jaipur'

# Dublicate values

In [123]:
# df.drop("ID" , axis=1 , inplace=True)
df.duplicated().sum()

np.int64(0)

In [124]:
df=df.drop_duplicates()

In [125]:
df

    ID    Name    Age  Gender    Salary    City
0    1     Ali   22.0    Male   25000.0  Jaipur
1    2    Sara   25.0  Female   30000.0   Delhi
2    3    John   27.0    Male   35000.0  Mumbai
3    4     Ali   22.0    Male   25000.0  Jaipur
4    5    Emma  150.0  Female   50895.0   Delhi
5    6     Tom   28.0    Male   45000.0  Jaipur
6    7    Anna   24.0  Female   32000.0  Jaipur
7    8   David   -5.0    Male   28000.0  Mumbai
8    9    Aman   27.0    Male   38000.0   Delhi
9   10   Priya   26.0  Female   42000.0  Jaipur
10  11   Rahul   29.0    Male   50000.0  Mumbai
11  12    Neha   31.0  Female   52000.0   Delhi
12  13   Karan   24.0    Male   34000.0  Jaipur
13  14   Meera   23.0  Female   31000.0  Mumbai
14  15   Arjun   35.0    Male   65000.0   Delhi
15  16  Simran   28.0  Female   47000.0  Jaipur
16  17   Rohit   30.0    Male   55000.0  Mumbai
17  18   Kavya   27.0  Female   44000.0   Delhi
18  19   Vikas  120.0    Male  250000.0  Jaipur
19  20   Pooja   27.0  Female   39000.0  Mumbai

In [133]:
# 1. Q1 aur Q3 nikalna
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

# 2. IQR calculate karna
IQR = Q3 - Q1

# 3. Boundaries set karna
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 4. Outliers ko filter karke naya clean dataframe banana
# df_clean = df[(df["Age"] >= lower_bound) & (df["Age"] <= upper_bound)]
# df[(df["Age"] >= lower_bound) & (df["Age"] <= upper_bound)]
df["Age"] >= lower_bound

0      True
1      True
2     False
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19    False
Name: Age, dtype: bool