In [1]:
# Warm-up Exercise: Simple function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False 
    return True

print("Is 7 prime?:", is_prime(7))

True

# Data Frame PANDAS

In [43]:
import numpy as np
import pandas as pd

##  Attribute,Description,
    Example Output
| Method | Description |
|--------|-------------|
| `.dtypes` |(Har column ka data type (int, float, object, etc.) batata hai.","Age: float64, Sex: object)  |
| `.shape` | ("DataFrame ka exact structure batata hai: (rows, columns)","(891, 12)") |
| `.size` | DataFrame ke andar total elements (cells) kitne hain (rows * columns).,10692 |
| `.ndim` | for dataframe  always return 2 dimensions |
| `.ndim`|Dimensions batata hai. DataFrame ke liye yeh hamesha 2 hota hai.|
|`.columns`|DataFrame ke saare column names ki list (Index) deta hai.,"Index(['PassengerId', 'Survived', ...])|
|`.index`|Rows ke labels ya range batata hai (kahan se shuru aur kahan khatam).,"RangeIndex(start=0, stop=891, step=1)|
|`.axes`|Row index aur Column index dono ko ek saath list me return karta hai.,"[Row RangeIndex, Column Index]|
|`.values`|DataFrame ke saare data ko ek NumPy array ke roop me convert kar deta hai.,"[[1, 0, 3, ...], [2, 1, 1, ...]]|
|`.empty`|"Agar DataFrame poora khaali hai (0 rows), toh True dega, nahi toh False.",False|
|`count()`||
|`memory_usage()`||
|`unique()`||
|`nunique()`||

In [44]:
df =pd.read_csv("../DataSet/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [141]:
# Displaying unique values and counts for columns
print("Unique gender categories in dataset:")
print(df["Sex"].unique())

print("\nNumber of unique values in each column:")
print(df.nunique())

print("\nCount of non-null values in each column:")
print(df.count())

print("\nNumber of unique names in 'Name' column:")
print(df["Name"].nunique())

print("\nTotal non-null names count:")
print(df["Name"].count())

np.int64(891)

In [145]:
# Alternate check for unique value counts and non-null entries
print("DataFrame Unique Counts per Column:\n", df.nunique())
print("\nDataFrame Non-Null Counts per Column:\n", df.count())

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [118]:
# rename column name 
df.rename(columns={"Sex" :"Gender"}, inplace=True)
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [122]:
# usecols 
df =pd.read_csv("../DataSet/train.csv",usecols=["Name","Sex", "Age"])
df

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [123]:
# nrows = 
df =pd.read_csv("../DataSet/train.csv",nrows=5)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [147]:
# skiprows = 
df =pd.read_csv("../DataSet/train.csv",skiprows=5)
df

,5,0,3,"Allen, Mr. William Henry",male,35,0.1,0.2,373450,8.05,Unnamed: 10,S
0,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
1,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
2,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
3,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
4,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
881,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
882,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
883,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
884,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
885,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [119]:
# Custom Columns Names
df =pd.read_csv("../DataSet/train.csv" ,names=["id" ,"Student","Age"]  )
df

,,,,,,,,,id,Student,Age
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

# Attributes for dataframe
| Method | Description |
|--------|-------------|
| `.dtypes` |  |
| `.shape` | (rows, columns) |
| `.size` | Total number of column |
| `.ndim` | for dataframe  always return 2 dimensions |

In [38]:
# Inspecting DataFrame structural attributes
print("dtypes (Data types of columns):\n", df.dtypes)
print("\nshape (Rows, Columns):", df.shape)
print("\nsize (Total elements = Rows * Columns):", df.size)
print("\nndim (Number of dimensions):", df.ndim)  # DataFrames are always 2-dimensional

dtype   :
 PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
shape   : (891, 12)
size    : 10692
ndim    : 2

# Viewing DataFrame Data

| Method | Description |
|--------|-------------|
| `head()` | First 5 rows |
| `tail()` | Last 5 rows |
| `sample()` | Random rows |
| `info()` | Column info & null counts |
| `describe()` | Statistical summary |

In [27]:
print("=== head(2) ===")
df.head(2) # head() give 5 rows by default

=== head(2) ===

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [28]:
print("\n=== tail(2) ===")
df.tail(2)  # y default 5

=== tail(2) ===

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [60]:
print("\n=== Sample() ===")
df.sample() # random row

=== Sample() ===

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.05,NaN,S

In [32]:
print("\n=== info() ===")
df.info()  # Column info & null counts

=== info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [31]:
print("\n=== describe() ===")
df.describe() # Statistical summary

=== describe() ===

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# With Excel Data

In [156]:
df= pd.read_excel("../DataSet/excel_data/Cola.xlsx")
df

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [162]:
print("Count :" , df.count())
# print("Count :" , df["Name"].count())

Count : Data provided by SimFin     3
Unnamed: 1                 97
Unnamed: 2                 82
Unnamed: 3                 82
Unnamed: 4                 82
Unnamed: 5                 82
Unnamed: 6                 82
Unnamed: 7                 82
Unnamed: 8                 90
Unnamed: 9                 92
Unnamed: 10                93
Unnamed: 11                93
dtype: int64